name: Python CI for CalculatorApp

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true

      - name: Run Tests
        run: |
          python -m unittest discover tests
      
       - name: Run Linter (flake8)
        run: |
          flake8 .
  
  docker-build:
    runs-on: ubuntu-latest
    needs: build-test-lint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t CalculatorApp:latest .

  fake-deploy:
    runs-on: ubuntu-latest
    needs: docker-build

    steps:
      - name: Fake Deploy Step
        run: |
          echo "✅ Application deployed successfully (simulated)!"